// <auto-generated />
using System;
using Concertable.B2B.Contract.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Concertable.B2B.Contract.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ContractDbContext))]
    [Migration("20260531191327_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("contract")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Concertable.B2B.Contract.Domain.Entities.ContractEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Contracts", "contract");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Concertable.Messaging.Domain.InboxMessageEntity", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConsumerName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("MessageId", "ConsumerName");

                    b.ToTable("Inbox", "messaging", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Concertable.Messaging.Domain.OutboxMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DispatchedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("LastError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("NextRetryAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Outbox", "messaging", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Concertable.B2B.Contract.Domain.Entities.DoorSplitContractEntity", b =>
                {
                    b.HasBaseType("Concertable.B2B.Contract.Domain.Entities.ContractEntity");

                    b.Property<decimal>("ArtistDoorPercent")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("DoorSplitContracts", "contract");
                });

            modelBuilder.Entity("Concertable.B2B.Contract.Domain.Entities.FlatFeeContractEntity", b =>
                {
                    b.HasBaseType("Concertable.B2B.Contract.Domain.Entities.ContractEntity");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("FlatFeeContracts", "contract");
                });

            modelBuilder.Entity("Concertable.B2B.Contract.Domain.Entities.VenueHireContractEntity", b =>
                {
                    b.HasBaseType("Concertable.B2B.Contract.Domain.Entities.ContractEntity");

                    b.Property<decimal>("HireFee")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("VenueHireContracts", "contract");
                });

            modelBuilder.Entity("Concertable.B2B.Contract.Domain.Entities.VersusContractEntity", b =>
                {
                    b.HasBaseType("Concertable.B2B.Contract.Domain.Entities.ContractEntity");

                    b.Property<decimal>("ArtistDoorPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Guarantee")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("VersusContracts", "contract");
                });

            modelBuilder.Entity("Concertable.B2B.Contract.Domain.Entities.DoorSplitContractEntity", b =>
                {
                    b.HasOne("Concertable.B2B.Contract.Domain.Entities.ContractEntity", null)
                        .WithOne()
                        .HasForeignKey("Concertable.B2B.Contract.Domain.Entities.DoorSplitContractEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Concertable.B2B.Contract.Domain.Entities.FlatFeeContractEntity", b =>
                {
                    b.HasOne("Concertable.B2B.Contract.Domain.Entities.ContractEntity", null)
                        .WithOne()
                        .HasForeignKey("Concertable.B2B.Contract.Domain.Entities.FlatFeeContractEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Concertable.B2B.Contract.Domain.Entities.VenueHireContractEntity", b =>
                {
                    b.HasOne("Concertable.B2B.Contract.Domain.Entities.ContractEntity", null)
                        .WithOne()
                        .HasForeignKey("Concertable.B2B.Contract.Domain.Entities.VenueHireContractEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Concertable.B2B.Contract.Domain.Entities.VersusContractEntity", b =>
                {
                    b.HasOne("Concertable.B2B.Contract.Domain.Entities.ContractEntity", null)
                        .WithOne()
                        .HasForeignKey("Concertable.B2B.Contract.Domain.Entities.VersusContractEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
