// <auto-generated />
using System;
using Concertable.Search.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace Concertable.Search.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SearchDbContext))]
    [Migration("20260525215731_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Concertable.Messaging.Domain.InboxMessageEntity", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConsumerName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("MessageId", "ConsumerName");

                    b.ToTable("Inbox", "messaging", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Concertable.Messaging.Domain.OutboxMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DispatchedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("LastError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Outbox", "messaging", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Concertable.Search.Domain.Models.ArtistReadModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Point>("Location")
                        .HasColumnType("geography");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Artists", "search");
                });

            modelBuilder.Entity("Concertable.Search.Domain.Models.ArtistReadModelGenre", b =>
                {
                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.HasKey("ArtistId", "Genre");

                    b.ToTable("ArtistGenres", "search");
                });

            modelBuilder.Entity("Concertable.Search.Domain.Models.ConcertReadModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<int>("AvailableTickets")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DatePosted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Point>("Location")
                        .HasColumnType("geography");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalTickets")
                        .HasColumnType("int");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("VenueId");

                    b.ToTable("Concerts", "search");
                });

            modelBuilder.Entity("Concertable.Search.Domain.Models.ConcertReadModelGenre", b =>
                {
                    b.Property<int>("ConcertId")
                        .HasColumnType("int");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.HasKey("ConcertId", "Genre");

                    b.ToTable("ConcertGenres", "search");
                });

            modelBuilder.Entity("Concertable.Search.Domain.Models.VenueReadModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Point>("Location")
                        .HasColumnType("geography");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Venues", "search");
                });

            modelBuilder.Entity("Concertable.Search.Domain.Projections.ArtistRatingProjection", b =>
                {
                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<double>("AverageRating")
                        .HasColumnType("float");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.HasKey("ArtistId");

                    b.ToTable("ArtistRatingProjections", "search");
                });

            modelBuilder.Entity("Concertable.Search.Domain.Projections.ConcertRatingProjection", b =>
                {
                    b.Property<int>("ConcertId")
                        .HasColumnType("int");

                    b.Property<double>("AverageRating")
                        .HasColumnType("float");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.HasKey("ConcertId");

                    b.ToTable("ConcertRatingProjections", "search");
                });

            modelBuilder.Entity("Concertable.Search.Domain.Projections.VenueRatingProjection", b =>
                {
                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.Property<double>("AverageRating")
                        .HasColumnType("float");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.HasKey("VenueId");

                    b.ToTable("VenueRatingProjections", "search");
                });

            modelBuilder.Entity("Concertable.Search.Domain.Models.ArtistReadModel", b =>
                {
                    b.OwnsOne("Concertable.Kernel.Address", "Address", b1 =>
                        {
                            b1.Property<int>("ArtistReadModelId")
                                .HasColumnType("int");

                            b1.Property<string>("County")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("County");

                            b1.Property<string>("Town")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Town");

                            b1.HasKey("ArtistReadModelId");

                            b1.ToTable("Artists", "search");

                            b1.WithOwner()
                                .HasForeignKey("ArtistReadModelId");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Concertable.Search.Domain.Models.ArtistReadModelGenre", b =>
                {
                    b.HasOne("Concertable.Search.Domain.Models.ArtistReadModel", "Artist")
                        .WithMany("ArtistGenres")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Concertable.Search.Domain.Models.ConcertReadModel", b =>
                {
                    b.HasOne("Concertable.Search.Domain.Models.ArtistReadModel", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Concertable.Search.Domain.Models.VenueReadModel", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Concertable.Search.Domain.Models.ConcertReadModelGenre", b =>
                {
                    b.HasOne("Concertable.Search.Domain.Models.ConcertReadModel", "Concert")
                        .WithMany("ConcertGenres")
                        .HasForeignKey("ConcertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concert");
                });

            modelBuilder.Entity("Concertable.Search.Domain.Models.VenueReadModel", b =>
                {
                    b.OwnsOne("Concertable.Kernel.Address", "Address", b1 =>
                        {
                            b1.Property<int>("VenueReadModelId")
                                .HasColumnType("int");

                            b1.Property<string>("County")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("County");

                            b1.Property<string>("Town")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Town");

                            b1.HasKey("VenueReadModelId");

                            b1.ToTable("Venues", "search");

                            b1.WithOwner()
                                .HasForeignKey("VenueReadModelId");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Concertable.Search.Domain.Models.ArtistReadModel", b =>
                {
                    b.Navigation("ArtistGenres");
                });

            modelBuilder.Entity("Concertable.Search.Domain.Models.ConcertReadModel", b =>
                {
                    b.Navigation("ConcertGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
