using Concertable.B2B.Seed.Contracts.Specs;
using Concertable.Seed.Identity;

namespace Concertable.B2B.Seed.Contracts;

public sealed partial class SeedCatalog
{
    public IReadOnlyList<VenueSeedSpec> Venues { get; } =
    [
        new VenueSeedSpec
        {
            VenueId   = 1,
            UserId    = SeedUsers.VenueManagerId(1),
            Name      = "The Grand Venue",
            About     = "The Grand Venue is the canonical Test County seed venue.",
            Avatar    = "avatar.jpg",
            BannerUrl = "grandvenue.jpg",
            County    = "Test County",
            Town      = "Test Town",
            Latitude  = 51.0,
            Longitude = 0.0,
            Email     = SeedUsers.VenueManagerEmail(1),
        },
        new VenueSeedSpec
        {
            VenueId   = 2,
            UserId    = SeedUsers.VenueManagerId(2),
            Name      = "Redhill Hall",
            About     = "Redhill Hall is a venue in Redhill.",
            Avatar    = "avatar.jpg",
            BannerUrl = "redhillhall.jpg",
            County    = "Surrey",
            Town      = "Redhill",
            Latitude  = 51.2362,
            Longitude = -0.1697,
            Email     = "redhillhall@test.com",
        },
        new VenueSeedSpec
        {
            VenueId   = 3,
            UserId    = SeedUsers.VenueManagerId(3),
            Name      = "Weybridge Pavilion",
            About     = "Weybridge Pavilion is a venue in Weybridge.",
            Avatar    = "avatar.jpg",
            BannerUrl = "weybridgepavilon.jpg",
            County    = "Surrey",
            Town      = "Weybridge",
            Latitude  = 51.3743,
            Longitude = -0.4515,
            Email     = "weybridgepavilion@test.com",
        },
        new VenueSeedSpec
        {
            VenueId   = 4,
            UserId    = SeedUsers.VenueManagerId(4),
            Name      = "Cobham Arts Centre",
            About     = "Cobham Arts Centre is a venue in Cobham.",
            Avatar    = "avatar.jpg",
            BannerUrl = "cobhamarts.jpg",
            County    = "Surrey",
            Town      = "Cobham",
            Latitude  = 51.3306,
            Longitude = -0.4080,
            Email     = "cobhamartscentre@test.com",
        },
        new VenueSeedSpec
        {
            VenueId   = 5,
            UserId    = SeedUsers.VenueManagerId(5),
            Name      = "Chertsey Arena",
            About     = "Chertsey Arena is a venue in Chertsey.",
            Avatar    = "avatar.jpg",
            BannerUrl = "chertseyarena.jpg",
            County    = "Surrey",
            Town      = "Chertsey",
            Latitude  = 51.3892,
            Longitude = -0.5071,
            Email     = "chertseyarena@test.com",
        },
        new VenueSeedSpec
        {
            VenueId   = 6,
            UserId    = SeedUsers.VenueManagerId(6),
            Name      = "Camden Electric Ballroom",
            About     = "Camden Electric Ballroom is a venue in London.",
            Avatar    = "avatar.jpg",
            BannerUrl = "camdenballroom.jpg",
            County    = "Greater London",
            Town      = "London",
            Latitude  = 51.5395,
            Longitude = -0.1426,
            Email     = "camdenelectricballroom@test.com",
        },
        new VenueSeedSpec
        {
            VenueId   = 7,
            UserId    = SeedUsers.VenueManagerId(7),
            Name      = "Manchester Night & Day Café",
            About     = "Manchester Night & Day Café is a venue in Manchester.",
            Avatar    = "avatar.jpg",
            BannerUrl = "manchesternightday.jpg",
            County    = "Greater Manchester",
            Town      = "Manchester",
            Latitude  = 53.4842,
            Longitude = -2.2351,
            Email     = "manchesternightandaycafe@test.com",
        },
        new VenueSeedSpec
        {
            VenueId   = 8,
            UserId    = SeedUsers.VenueManagerId(8),
            Name      = "Birmingham O2 Institute",
            About     = "Birmingham O2 Institute is a venue in Birmingham.",
            Avatar    = "avatar.jpg",
            BannerUrl = "birminghamo2.jpg",
            County    = "West Midlands",
            Town      = "Birmingham",
            Latitude  = 52.4774,
            Longitude = -1.8861,
            Email     = "birminghamo2institute@test.com",
        },
        new VenueSeedSpec
        {
            VenueId   = 9,
            UserId    = SeedUsers.VenueManagerId(9),
            Name      = "Edinburgh Usher Hall",
            About     = "Edinburgh Usher Hall is a venue in Edinburgh.",
            Avatar    = "avatar.jpg",
            BannerUrl = "edinburghusher.jpg",
            County    = "City of Edinburgh",
            Town      = "Edinburgh",
            Latitude  = 55.9474,
            Longitude = -3.2042,
            Email     = "edinburghusherhall@test.com",
        },
        new VenueSeedSpec
        {
            VenueId   = 10,
            UserId    = SeedUsers.VenueManagerId(10),
            Name      = "Liverpool Philharmonic Hall",
            About     = "Liverpool Philharmonic Hall is a venue in Liverpool.",
            Avatar    = "avatar.jpg",
            BannerUrl = "liverpoolphilharmonic.jpg",
            County    = "Merseyside",
            Town      = "Liverpool",
            Latitude  = 53.4036,
            Longitude = -2.9748,
            Email     = "liverpoolphilharmonichall@test.com",
        },
        new VenueSeedSpec
        {
            VenueId   = 11,
            UserId    = SeedUsers.VenueManagerId(11),
            Name      = "Leeds Brudenell Social Club",
            About     = "Leeds Brudenell Social Club is a venue in Leeds.",
            Avatar    = "avatar.jpg",
            BannerUrl = "leedsbrudenell.jpg",
            County    = "West Yorkshire",
            Town      = "Leeds",
            Latitude  = 53.8202,
            Longitude = -1.5639,
            Email     = "leedsbrudenellsocialclub@test.com",
        },
        new VenueSeedSpec
        {
            VenueId   = 12,
            UserId    = SeedUsers.VenueManagerId(12),
            Name      = "Glasgow Barrowland Ballroom",
            About     = "Glasgow Barrowland Ballroom is a venue in Glasgow.",
            Avatar    = "avatar.jpg",
            BannerUrl = "glasgowbarrowland.jpg",
            County    = "Glasgow City",
            Town      = "Glasgow",
            Latitude  = 55.8585,
            Longitude = -4.2370,
            Email     = "glasgowbarrowlandballroom@test.com",
        },
        new VenueSeedSpec
        {
            VenueId   = 13,
            UserId    = SeedUsers.VenueManagerId(13),
            Name      = "Sheffield Leadmill",
            About     = "Sheffield Leadmill is a venue in Sheffield.",
            Avatar    = "avatar.jpg",
            BannerUrl = "sheffieldleadmill.jpg",
            County    = "South Yorkshire",
            Town      = "Sheffield",
            Latitude  = 53.3760,
            Longitude = -1.4683,
            Email     = "sheffieldleadmill@test.com",
        },
        new VenueSeedSpec
        {
            VenueId   = 14,
            UserId    = SeedUsers.VenueManagerId(14),
            Name      = "Nottingham Rock City",
            About     = "Nottingham Rock City is a venue in Nottingham.",
            Avatar    = "avatar.jpg",
            BannerUrl = "nottinghamrockcity.jpg",
            County    = "Nottinghamshire",
            Town      = "Nottingham",
            Latitude  = 52.9586,
            Longitude = -1.1543,
            Email     = "nottinghamrockcity@test.com",
        },
        new VenueSeedSpec
        {
            VenueId   = 15,
            UserId    = SeedUsers.VenueManagerId(15),
            Name      = "Bristol Thekla",
            About     = "Bristol Thekla is a venue in Bristol.",
            Avatar    = "avatar.jpg",
            BannerUrl = "bristolthekla.jpg",
            County    = "Bristol",
            Town      = "Bristol",
            Latitude  = 51.4495,
            Longitude = -2.5928,
            Email     = "bristolthekla@test.com",
        },
        new VenueSeedSpec
        {
            VenueId   = 16,
            UserId    = SeedUsers.VenueManagerId(16),
            Name      = "Brighton Concorde 2",
            About     = "Brighton Concorde 2 is a venue in Brighton.",
            Avatar    = "avatar.jpg",
            BannerUrl = "brightonconcorde2.jpg",
            County    = "East Sussex",
            Town      = "Brighton",
            Latitude  = 50.8200,
            Longitude = -0.1262,
            Email     = "brightonconcorde2@test.com",
        },
        new VenueSeedSpec
        {
            VenueId   = 17,
            UserId    = SeedUsers.VenueManagerId(17),
            Name      = "Cardiff Tramshed",
            About     = "Cardiff Tramshed is a venue in Cardiff.",
            Avatar    = "avatar.jpg",
            BannerUrl = "cardifftramshed.jpg",
            County    = "Cardiff",
            Town      = "Cardiff",
            Latitude  = 51.4774,
            Longitude = -3.1837,
            Email     = "cardifftramshed@test.com",
        },
        new VenueSeedSpec
        {
            VenueId   = 18,
            UserId    = SeedUsers.VenueManagerId(18),
            Name      = "Newcastle O2 Academy",
            About     = "Newcastle O2 Academy is a venue in Newcastle.",
            Avatar    = "avatar.jpg",
            BannerUrl = "newcastleo2.jpg",
            County    = "Tyne and Wear",
            Town      = "Newcastle",
            Latitude  = 54.9696,
            Longitude = -1.6109,
            Email     = "newcastleo2academy@test.com",
        },
        new VenueSeedSpec
        {
            VenueId   = 19,
            UserId    = SeedUsers.VenueManagerId(19),
            Name      = "Oxford O2 Academy",
            About     = "Oxford O2 Academy is a venue in Oxford.",
            Avatar    = "avatar.jpg",
            BannerUrl = "oxfordo2.jpg",
            County    = "Oxfordshire",
            Town      = "Oxford",
            Latitude  = 51.7521,
            Longitude = -1.2602,
            Email     = "oxfordo2academy@test.com",
        },
        new VenueSeedSpec
        {
            VenueId   = 20,
            UserId    = SeedUsers.VenueManagerId(20),
            Name      = "Cambridge Corn Exchange",
            About     = "Cambridge Corn Exchange is a venue in Cambridge.",
            Avatar    = "avatar.jpg",
            BannerUrl = "cambridgecornexchange.jpg",
            County    = "Cambridgeshire",
            Town      = "Cambridge",
            Latitude  = 52.2046,
            Longitude = 0.1199,
            Email     = "cambridgecornexchange@test.com",
        },
        new VenueSeedSpec
        {
            VenueId   = 21,
            UserId    = SeedUsers.VenueManagerId(21),
            Name      = "Bath Komedia",
            About     = "Bath Komedia is a venue in Bath.",
            Avatar    = "avatar.jpg",
            BannerUrl = "bathkomedia.jpg",
            County    = "Somerset",
            Town      = "Bath",
            Latitude  = 51.3789,
            Longitude = -2.3623,
            Email     = "bathkomedia@test.com",
        },
        new VenueSeedSpec
        {
            VenueId   = 22,
            UserId    = SeedUsers.VenueManagerId(22),
            Name      = "Aberdeen The Lemon Tree",
            About     = "Aberdeen The Lemon Tree is a venue in Aberdeen.",
            Avatar    = "avatar.jpg",
            BannerUrl = "aberdeenlemontree.jpg",
            County    = "Aberdeen City",
            Town      = "Aberdeen",
            Latitude  = 57.1496,
            Longitude = -2.0962,
            Email     = "aberdeenthelemontree@test.com",
        },
        new VenueSeedSpec
        {
            VenueId   = 23,
            UserId    = SeedUsers.VenueManagerId(23),
            Name      = "York Barbican",
            About     = "York Barbican is a venue in York.",
            Avatar    = "avatar.jpg",
            BannerUrl = "yorkbarbican.jpg",
            County    = "North Yorkshire",
            Town      = "York",
            Latitude  = 53.9543,
            Longitude = -1.0741,
            Email     = "yorkbarbican@test.com",
        },
        new VenueSeedSpec
        {
            VenueId   = 24,
            UserId    = SeedUsers.VenueManagerId(24),
            Name      = "Belfast Limelight",
            About     = "Belfast Limelight is a venue in Belfast.",
            Avatar    = "avatar.jpg",
            BannerUrl = "belfastlimelight.jpg",
            County    = "Antrim",
            Town      = "Belfast",
            Latitude  = 54.5944,
            Longitude = -5.9303,
            Email     = "belfastlimelight@test.com",
        },
        new VenueSeedSpec
        {
            VenueId   = 25,
            UserId    = SeedUsers.VenueManagerId(25),
            Name      = "Dublin Vicar Street",
            About     = "Dublin Vicar Street is a venue in Dublin.",
            Avatar    = "avatar.jpg",
            BannerUrl = "dublinvicarstreet.jpg",
            County    = "Dublin",
            Town      = "Dublin",
            Latitude  = 53.3422,
            Longitude = -6.2756,
            Email     = "dublinvicarstreet@test.com",
        },
        new VenueSeedSpec
        {
            VenueId   = 26,
            UserId    = SeedUsers.VenueManagerId(26),
            Name      = "Norwich Waterfront",
            About     = "Norwich Waterfront is a venue in Norwich.",
            Avatar    = "avatar.jpg",
            BannerUrl = "norwichwaterfront.jpg",
            County    = "Norfolk",
            Town      = "Norwich",
            Latitude  = 52.6258,
            Longitude = 1.2972,
            Email     = "norwichwaterfront@test.com",
        },
        new VenueSeedSpec
        {
            VenueId   = 27,
            UserId    = SeedUsers.VenueManagerId(27),
            Name      = "Exeter Phoenix",
            About     = "Exeter Phoenix is a venue in Exeter.",
            Avatar    = "avatar.jpg",
            BannerUrl = "exeterphoenix.jpg",
            County    = "Devon",
            Town      = "Exeter",
            Latitude  = 50.7251,
            Longitude = -3.5314,
            Email     = "exeterphoenix@test.com",
        },
        new VenueSeedSpec
        {
            VenueId   = 28,
            UserId    = SeedUsers.VenueManagerId(28),
            Name      = "Southampton Engine Rooms",
            About     = "Southampton Engine Rooms is a venue in Southampton.",
            Avatar    = "avatar.jpg",
            BannerUrl = "southamptonengine.jpg",
            County    = "Hampshire",
            Town      = "Southampton",
            Latitude  = 50.9061,
            Longitude = -1.4039,
            Email     = "southamptonenginerooms@test.com",
        },
        new VenueSeedSpec
        {
            VenueId   = 29,
            UserId    = SeedUsers.VenueManagerId(29),
            Name      = "Hull The Welly Club",
            About     = "Hull The Welly Club is a venue in Hull.",
            Avatar    = "avatar.jpg",
            BannerUrl = "hullwellyclub.jpg",
            County    = "East Riding of Yorkshire",
            Town      = "Hull",
            Latitude  = 53.7459,
            Longitude = -0.3367,
            Email     = "hullthewellyclub@test.com",
        },
        new VenueSeedSpec
        {
            VenueId   = 30,
            UserId    = SeedUsers.VenueManagerId(30),
            Name      = "Plymouth Junction",
            About     = "Plymouth Junction is a venue in Plymouth.",
            Avatar    = "avatar.jpg",
            BannerUrl = "plymouthjunction.jpg",
            County    = "Devon",
            Town      = "Plymouth",
            Latitude  = 50.3755,
            Longitude = -4.1427,
            Email     = "plymouthjunction@test.com",
        },
        new VenueSeedSpec
        {
            VenueId   = 31,
            UserId    = SeedUsers.VenueManagerId(31),
            Name      = "Swansea Sin City",
            About     = "Swansea Sin City is a venue in Swansea.",
            Avatar    = "avatar.jpg",
            BannerUrl = "swanseasincity.jpg",
            County    = "Swansea",
            Town      = "Swansea",
            Latitude  = 51.6207,
            Longitude = -3.9436,
            Email     = "swanseasincity@test.com",
        },
        new VenueSeedSpec
        {
            VenueId   = 32,
            UserId    = SeedUsers.VenueManagerId(32),
            Name      = "Inverness Ironworks",
            About     = "Inverness Ironworks is a venue in Inverness.",
            Avatar    = "avatar.jpg",
            BannerUrl = "invernessironworks.jpg",
            County    = "Highland",
            Town      = "Inverness",
            Latitude  = 57.4778,
            Longitude = -4.2247,
            Email     = "invernessironworks@test.com",
        },
        new VenueSeedSpec
        {
            VenueId   = 33,
            UserId    = SeedUsers.VenueManagerId(33),
            Name      = "Stirling Albert Halls",
            About     = "Stirling Albert Halls is a venue in Stirling.",
            Avatar    = "avatar.jpg",
            BannerUrl = "stirlingalberthalls.jpg",
            County    = "Stirling",
            Town      = "Stirling",
            Latitude  = 56.1166,
            Longitude = -3.9369,
            Email     = "stirlingalberthalls@test.com",
        },
        new VenueSeedSpec
        {
            VenueId   = 34,
            UserId    = SeedUsers.VenueManagerId(34),
            Name      = "Dundee Fat Sams",
            About     = "Dundee Fat Sams is a venue in Dundee.",
            Avatar    = "avatar.jpg",
            BannerUrl = "dundeefatsams.jpg",
            County    = "Dundee City",
            Town      = "Dundee",
            Latitude  = 56.4607,
            Longitude = -2.9707,
            Email     = "dundeefatsams@test.com",
        },
    ];
}
