using Concertable.B2B.Seed.Contracts.Specs;
using Concertable.Contracts;
using Concertable.Seed.Identity;

namespace Concertable.B2B.Seed.Contracts;

public sealed partial class SeedCatalog
{
    public IReadOnlyList<ArtistSeedSpec> Artists { get; } =
    [
        new ArtistSeedSpec
        {
            ArtistId  = 1,
            UserId    = SeedUsers.ArtistManagerId(1),
            Name      = "The Rockers",
            About     = "The Rockers is an artist based in Loughborough.",
            Avatar    = "avatar.jpg",
            BannerUrl = "rockers.jpg",
            County    = "Leicestershire",
            Town      = "Loughborough",
            Latitude  = 52.7721,
            Longitude = -1.2062,
            Email     = "therockers@test.com",
            Genres    = [Genre.Rock, Genre.Pop, Genre.Jazz],
        },
        new ArtistSeedSpec
        {
            ArtistId  = 2,
            UserId    = SeedUsers.ArtistManagerId(2),
            Name      = "Indie Vibes",
            About     = "Indie Vibes is an artist based in London.",
            Avatar    = "avatar.jpg",
            BannerUrl = "indievibes.jpg",
            County    = "Greater London",
            Town      = "London",
            Latitude  = 51.5074,
            Longitude = -0.1278,
            Email     = "indievibes@test.com",
            Genres    = [Genre.Rock, Genre.Electronic, Genre.HipHop],
        },
        new ArtistSeedSpec
        {
            ArtistId  = 3,
            UserId    = SeedUsers.ArtistManagerId(3),
            Name      = "Electronic Pulse",
            About     = "Electronic Pulse is an artist based in Manchester.",
            Avatar    = "avatar.jpg",
            BannerUrl = "electronicpulse.jpg",
            County    = "Greater Manchester",
            Town      = "Manchester",
            Latitude  = 53.4808,
            Longitude = -2.2426,
            Email     = "electronicpulse@test.com",
            Genres    = [Genre.Electronic, Genre.Jazz],
        },
        new ArtistSeedSpec
        {
            ArtistId  = 4,
            UserId    = SeedUsers.ArtistManagerId(4),
            Name      = "Hip-Hop Flow",
            About     = "Hip-Hop Flow is an artist based in Guildford.",
            Avatar    = "avatar.jpg",
            BannerUrl = "hiphopflow.jpg",
            County    = "Surrey",
            Town      = "Guildford",
            Latitude  = 51.2362,
            Longitude = -0.5704,
            Email     = "hip-hopflow@test.com",
            Genres    = [Genre.HipHop],
        },
        new ArtistSeedSpec
        {
            ArtistId  = 5,
            UserId    = SeedUsers.ArtistManagerId(5),
            Name      = "Jazz Masters",
            About     = "Jazz Masters is an artist based in Leeds.",
            Avatar    = "avatar.jpg",
            BannerUrl = "jazzmaster.jpg",
            County    = "West Yorkshire",
            Town      = "Leeds",
            Latitude  = 53.8008,
            Longitude = -1.5491,
            Email     = "jazzmasters@test.com",
            Genres    = [Genre.Indie, Genre.Jazz],
        },
        new ArtistSeedSpec
        {
            ArtistId  = 6,
            UserId    = SeedUsers.ArtistManagerId(6),
            Name      = "Always Punks",
            About     = "Always Punks is an artist based in Birmingham.",
            Avatar    = "avatar.jpg",
            BannerUrl = "alwayspunks.jpg",
            County    = "West Midlands",
            Town      = "Birmingham",
            Latitude  = 52.4862,
            Longitude = -1.8904,
            Email     = "alwayspunks@test.com",
            Genres    = [Genre.Rock, Genre.Indie],
        },
        new ArtistSeedSpec
        {
            ArtistId  = 7,
            UserId    = SeedUsers.ArtistManagerId(7),
            Name      = "The Hollow Frequencies",
            About     = "The Hollow Frequencies is an artist based in Newcastle.",
            Avatar    = "avatar.jpg",
            BannerUrl = "hollowfrequencies.jpg",
            County    = "Tyne and Wear",
            Town      = "Newcastle",
            Latitude  = 54.9783,
            Longitude = -1.6178,
            Email     = "thehollowfrequencies@test.com",
            Genres    = [Genre.Pop],
        },
        new ArtistSeedSpec
        {
            ArtistId  = 8,
            UserId    = SeedUsers.ArtistManagerId(8),
            Name      = "Neon Foxes",
            About     = "Neon Foxes is an artist based in Sheffield.",
            Avatar    = "avatar.jpg",
            BannerUrl = "neonfoxes.jpg",
            County    = "South Yorkshire",
            Town      = "Sheffield",
            Latitude  = 53.3811,
            Longitude = -1.4701,
            Email     = "neonfoxes@test.com",
            Genres    = [Genre.HipHop, Genre.Pop],
        },
        new ArtistSeedSpec
        {
            ArtistId  = 9,
            UserId    = SeedUsers.ArtistManagerId(9),
            Name      = "Velvet Static",
            About     = "Velvet Static is an artist based in Liverpool.",
            Avatar    = "avatar.jpg",
            BannerUrl = "velvetstatic.jpg",
            County    = "Merseyside",
            Town      = "Liverpool",
            Latitude  = 53.4084,
            Longitude = -2.9916,
            Email     = "velvetstatic@test.com",
            Genres    = [Genre.Electronic, Genre.Jazz],
        },
        new ArtistSeedSpec
        {
            ArtistId  = 10,
            UserId    = SeedUsers.ArtistManagerId(10),
            Name      = "Echo Bloom",
            About     = "Echo Bloom is an artist based in Bristol.",
            Avatar    = "avatar.jpg",
            BannerUrl = "echobloom.jpg",
            County    = "Bristol",
            Town      = "Bristol",
            Latitude  = 51.4545,
            Longitude = -2.5879,
            Email     = "echobloom@test.com",
            Genres    = [Genre.Rock, Genre.DnB],
        },
        new ArtistSeedSpec
        {
            ArtistId  = 11,
            UserId    = SeedUsers.ArtistManagerId(11),
            Name      = "The Wild Chords",
            About     = "The Wild Chords is an artist based in Nottingham.",
            Avatar    = "avatar.jpg",
            BannerUrl = "wildchords.jpg",
            County    = "Nottinghamshire",
            Town      = "Nottingham",
            Latitude  = 52.9548,
            Longitude = -1.1581,
            Email     = "thewildchords@test.com",
            Genres    = [Genre.Indie, Genre.Rock],
        },
        new ArtistSeedSpec
        {
            ArtistId  = 12,
            UserId    = SeedUsers.ArtistManagerId(12),
            Name      = "Glitch & Glow",
            About     = "Glitch & Glow is an artist based in Southampton.",
            Avatar    = "avatar.jpg",
            BannerUrl = "glitchandglow.jpg",
            County    = "Hampshire",
            Town      = "Southampton",
            Latitude  = 50.9097,
            Longitude = -1.4043,
            Email     = "glitch&glow@test.com",
            Genres    = [Genre.Pop],
        },
        new ArtistSeedSpec
        {
            ArtistId  = 13,
            UserId    = SeedUsers.ArtistManagerId(13),
            Name      = "Sonic Mirage",
            About     = "Sonic Mirage is an artist based in Preston.",
            Avatar    = "avatar.jpg",
            BannerUrl = "sonicmirage.jpg",
            County    = "Lancashire",
            Town      = "Preston",
            Latitude  = 53.7632,
            Longitude = -2.7031,
            Email     = "sonicmirage@test.com",
            Genres    = [Genre.Indie, Genre.Electronic],
        },
        new ArtistSeedSpec
        {
            ArtistId  = 14,
            UserId    = SeedUsers.ArtistManagerId(14),
            Name      = "Neon Echoes",
            About     = "Neon Echoes is an artist based in Cambridge.",
            Avatar    = "avatar.jpg",
            BannerUrl = "neonechoes.jpg",
            County    = "Cambridgeshire",
            Town      = "Cambridge",
            Latitude  = 52.2053,
            Longitude = 0.1218,
            Email     = "neonechoes@test.com",
            Genres    = [Genre.HipHop],
        },
        new ArtistSeedSpec
        {
            ArtistId  = 15,
            UserId    = SeedUsers.ArtistManagerId(15),
            Name      = "Dreamwave Collective",
            About     = "Dreamwave Collective is an artist based in Oxford.",
            Avatar    = "avatar.jpg",
            BannerUrl = "dreamwavecollective.jpg",
            County    = "Oxfordshire",
            Town      = "Oxford",
            Latitude  = 51.7520,
            Longitude = -1.2577,
            Email     = "dreamwavecollective@test.com",
            Genres    = [Genre.DnB],
        },
        new ArtistSeedSpec
        {
            ArtistId  = 16,
            UserId    = SeedUsers.ArtistManagerId(16),
            Name      = "Synth Pulse",
            About     = "Synth Pulse is an artist based in Loughborough.",
            Avatar    = "avatar.jpg",
            BannerUrl = "synthpulse.jpg",
            County    = "Leicestershire",
            Town      = "Loughborough",
            Latitude  = 52.7721,
            Longitude = -1.2062,
            Email     = "synthpulse@test.com",
            Genres    = [Genre.Rock],
        },
        new ArtistSeedSpec
        {
            ArtistId  = 17,
            UserId    = SeedUsers.ArtistManagerId(17),
            Name      = "The Brass Poets",
            About     = "The Brass Poets is an artist based in London.",
            Avatar    = "avatar.jpg",
            BannerUrl = "brasspoets.jpg",
            County    = "Greater London",
            Town      = "London",
            Latitude  = 51.5074,
            Longitude = -0.1278,
            Email     = "thebrasspoets@test.com",
            Genres    = [Genre.Jazz],
        },
        new ArtistSeedSpec
        {
            ArtistId  = 18,
            UserId    = SeedUsers.ArtistManagerId(18),
            Name      = "Groove Alchemy",
            About     = "Groove Alchemy is an artist based in Manchester.",
            Avatar    = "avatar.jpg",
            BannerUrl = "groovealchemy.jpg",
            County    = "Greater Manchester",
            Town      = "Manchester",
            Latitude  = 53.4808,
            Longitude = -2.2426,
            Email     = "groovealchemy@test.com",
            Genres    = [Genre.Indie],
        },
        new ArtistSeedSpec
        {
            ArtistId  = 19,
            UserId    = SeedUsers.ArtistManagerId(19),
            Name      = "Velvet Rhymes",
            About     = "Velvet Rhymes is an artist based in Guildford.",
            Avatar    = "avatar.jpg",
            BannerUrl = "velvetrhymes.jpg",
            County    = "Surrey",
            Town      = "Guildford",
            Latitude  = 51.2362,
            Longitude = -0.5704,
            Email     = "velvetrhymes@test.com",
            Genres    = [Genre.HipHop],
        },
        new ArtistSeedSpec
        {
            ArtistId  = 20,
            UserId    = SeedUsers.ArtistManagerId(20),
            Name      = "The Lo-Fi Syndicate",
            About     = "The Lo-Fi Syndicate is an artist based in Leeds.",
            Avatar    = "avatar.jpg",
            BannerUrl = "lofisyndicate.jpg",
            County    = "West Yorkshire",
            Town      = "Leeds",
            Latitude  = 53.8008,
            Longitude = -1.5491,
            Email     = "thelo-fisyndicate@test.com",
            Genres    = [Genre.DnB],
        },
        new ArtistSeedSpec
        {
            ArtistId  = 21,
            UserId    = SeedUsers.ArtistManagerId(21),
            Name      = "Beats & Blue Notes",
            About     = "Beats & Blue Notes is an artist based in Birmingham.",
            Avatar    = "avatar.jpg",
            BannerUrl = "beatsbluenotes.jpg",
            County    = "West Midlands",
            Town      = "Birmingham",
            Latitude  = 52.4862,
            Longitude = -1.8904,
            Email     = "beats&bluenotes@test.com",
            Genres    = [Genre.House],
        },
        new ArtistSeedSpec
        {
            ArtistId  = 22,
            UserId    = SeedUsers.ArtistManagerId(22),
            Name      = "Bass Pilots",
            About     = "Bass Pilots is an artist based in Newcastle.",
            Avatar    = "avatar.jpg",
            BannerUrl = "basspilots.jpg",
            County    = "Tyne and Wear",
            Town      = "Newcastle",
            Latitude  = 54.9783,
            Longitude = -1.6178,
            Email     = "basspilots@test.com",
            Genres    = [Genre.Rock],
        },
        new ArtistSeedSpec
        {
            ArtistId  = 23,
            UserId    = SeedUsers.ArtistManagerId(23),
            Name      = "The Digital Prophets",
            About     = "The Digital Prophets is an artist based in Sheffield.",
            Avatar    = "avatar.jpg",
            BannerUrl = "digitalprophets.jpg",
            County    = "South Yorkshire",
            Town      = "Sheffield",
            Latitude  = 53.3811,
            Longitude = -1.4701,
            Email     = "thedigitalprophets@test.com",
            Genres    = [Genre.Electronic],
        },
        new ArtistSeedSpec
        {
            ArtistId  = 24,
            UserId    = SeedUsers.ArtistManagerId(24),
            Name      = "Neon Bass Theory",
            About     = "Neon Bass Theory is an artist based in Liverpool.",
            Avatar    = "avatar.jpg",
            BannerUrl = "neonbasstheory.jpg",
            County    = "Merseyside",
            Town      = "Liverpool",
            Latitude  = 53.4084,
            Longitude = -2.9916,
            Email     = "neonbasstheory@test.com",
            Genres    = [Genre.Indie],
        },
        new ArtistSeedSpec
        {
            ArtistId  = 25,
            UserId    = SeedUsers.ArtistManagerId(25),
            Name      = "Wavelength 303",
            About     = "Wavelength 303 is an artist based in Bristol.",
            Avatar    = "avatar.jpg",
            BannerUrl = "wavelength303.jpg",
            County    = "Bristol",
            Town      = "Bristol",
            Latitude  = 51.4545,
            Longitude = -2.5879,
            Email     = "wavelength303@test.com",
            Genres    = [Genre.Pop],
        },
        new ArtistSeedSpec
        {
            ArtistId  = 26,
            UserId    = SeedUsers.ArtistManagerId(26),
            Name      = "Gravity Loops",
            About     = "Gravity Loops is an artist based in Nottingham.",
            Avatar    = "avatar.jpg",
            BannerUrl = "gravityloops.jpg",
            County    = "Nottinghamshire",
            Town      = "Nottingham",
            Latitude  = 52.9548,
            Longitude = -1.1581,
            Email     = "gravityloops@test.com",
            Genres    = [Genre.Rock],
        },
        new ArtistSeedSpec
        {
            ArtistId  = 27,
            UserId    = SeedUsers.ArtistManagerId(27),
            Name      = "The Golden Reverie",
            About     = "The Golden Reverie is an artist based in Southampton.",
            Avatar    = "avatar.jpg",
            BannerUrl = "goldenreverie.jpg",
            County    = "Hampshire",
            Town      = "Southampton",
            Latitude  = 50.9097,
            Longitude = -1.4043,
            Email     = "thegoldenreverie@test.com",
            Genres    = [Genre.House],
        },
        new ArtistSeedSpec
        {
            ArtistId  = 28,
            UserId    = SeedUsers.ArtistManagerId(28),
            Name      = "Fable Sound",
            About     = "Fable Sound is an artist based in Preston.",
            Avatar    = "avatar.jpg",
            BannerUrl = "fablesound.jpg",
            County    = "Lancashire",
            Town      = "Preston",
            Latitude  = 53.7632,
            Longitude = -2.7031,
            Email     = "fablesound@test.com",
            Genres    = [Genre.Electronic],
        },
        new ArtistSeedSpec
        {
            ArtistId  = 29,
            UserId    = SeedUsers.ArtistManagerId(29),
            Name      = "Moonlight Static",
            About     = "Moonlight Static is an artist based in Cambridge.",
            Avatar    = "avatar.jpg",
            BannerUrl = "moonlightstatic.jpg",
            County    = "Cambridgeshire",
            Town      = "Cambridge",
            Latitude  = 52.2053,
            Longitude = 0.1218,
            Email     = "moonlightstatic@test.com",
            Genres    = [Genre.DnB],
        },
        new ArtistSeedSpec
        {
            ArtistId  = 30,
            UserId    = SeedUsers.ArtistManagerId(30),
            Name      = "The Chromatics",
            About     = "The Chromatics is an artist based in Oxford.",
            Avatar    = "avatar.jpg",
            BannerUrl = "thechromatics.jpg",
            County    = "Oxfordshire",
            Town      = "Oxford",
            Latitude  = 51.7520,
            Longitude = -1.2577,
            Email     = "thechromatics@test.com",
            Genres    = [Genre.Jazz],
        },
        new ArtistSeedSpec
        {
            ArtistId  = 31,
            UserId    = SeedUsers.ArtistManagerId(31),
            Name      = "Echo Reverberation",
            About     = "Echo Reverberation is an artist based in Loughborough.",
            Avatar    = "avatar.jpg",
            BannerUrl = "echoreverberation.jpg",
            County    = "Leicestershire",
            Town      = "Loughborough",
            Latitude  = 52.7721,
            Longitude = -1.2062,
            Email     = "echoreverberation@test.com",
            Genres    = [Genre.Indie],
        },
        new ArtistSeedSpec
        {
            ArtistId  = 32,
            UserId    = SeedUsers.ArtistManagerId(32),
            Name      = "Midnight Reverie",
            About     = "Midnight Reverie is an artist based in London.",
            Avatar    = "avatar.jpg",
            BannerUrl = "midnightreverie.jpg",
            County    = "Greater London",
            Town      = "London",
            Latitude  = 51.5074,
            Longitude = -0.1278,
            Email     = "midnightreverie@test.com",
            Genres    = [Genre.Rock],
        },
        new ArtistSeedSpec
        {
            ArtistId  = 33,
            UserId    = SeedUsers.ArtistManagerId(33),
            Name      = "Static Wolves",
            About     = "Static Wolves is an artist based in Manchester.",
            Avatar    = "avatar.jpg",
            BannerUrl = "staticwolves.jpg",
            County    = "Greater Manchester",
            Town      = "Manchester",
            Latitude  = 53.4808,
            Longitude = -2.2426,
            Email     = "staticwolves@test.com",
            Genres    = [Genre.HipHop],
        },
        new ArtistSeedSpec
        {
            ArtistId  = 34,
            UserId    = SeedUsers.ArtistManagerId(34),
            Name      = "Echo Collapse",
            About     = "Echo Collapse is an artist based in Guildford.",
            Avatar    = "avatar.jpg",
            BannerUrl = "echocollapse.jpg",
            County    = "Surrey",
            Town      = "Guildford",
            Latitude  = 51.2362,
            Longitude = -0.5704,
            Email     = "echocollapse@test.com",
            Genres    = [Genre.Pop],
        },
    ];
}
