/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as StripeReturnRouteImport } from './routes/stripe-return'
import { Route as StripeRefreshRouteImport } from './routes/stripe-refresh'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FailRouteImport } from './routes/fail'
import { Route as VenueRouteRouteImport } from './routes/_venue/route'
import { Route as VenueIndexRouteImport } from './routes/_venue/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as VenueCreateRouteImport } from './routes/_venue/create'
import { Route as VenueSettingsRouteRouteImport } from './routes/_venue/settings/route'
import { Route as VenueSettingsIndexRouteImport } from './routes/_venue/settings/index'
import { Route as VenueMyIndexRouteImport } from './routes/_venue/my/index'
import { Route as VenueFindIndexRouteImport } from './routes/_venue/find/index'
import { Route as VenueSettingsPaymentRouteImport } from './routes/_venue/settings/payment'
import { Route as VenueFindVenueIdRouteImport } from './routes/_venue/find/venue.$id'
import { Route as VenueFindConcertIdRouteImport } from './routes/_venue/find/concert.$id'
import { Route as VenueFindArtistIdRouteImport } from './routes/_venue/find/artist.$id'
import { Route as VenueApplicationsApplicationIdCheckoutRouteImport } from './routes/_venue/applications/$applicationId/checkout'
import { Route as VenueApplicationsApplicationIdAcceptRouteImport } from './routes/_venue/applications/$applicationId/accept'
import { Route as VenueMyOpportunitiesOpportunityIdApplicationsRouteImport } from './routes/_venue/my/opportunities/$opportunityId/applications'
import { Route as VenueMyConcertsConcertIdRouteImport } from './routes/_venue/my/concerts/concert.$id'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const StripeReturnRoute = StripeReturnRouteImport.update({
  id: '/stripe-return',
  path: '/stripe-return',
  getParentRoute: () => rootRouteImport,
} as any)
const StripeRefreshRoute = StripeRefreshRouteImport.update({
  id: '/stripe-refresh',
  path: '/stripe-refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FailRoute = FailRouteImport.update({
  id: '/fail',
  path: '/fail',
  getParentRoute: () => rootRouteImport,
} as any)
const VenueRouteRoute = VenueRouteRouteImport.update({
  id: '/_venue',
  getParentRoute: () => rootRouteImport,
} as any)
const VenueIndexRoute = VenueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VenueRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const VenueCreateRoute = VenueCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => VenueRouteRoute,
} as any)
const VenueSettingsRouteRoute = VenueSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => VenueRouteRoute,
} as any)
const VenueSettingsIndexRoute = VenueSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VenueSettingsRouteRoute,
} as any)
const VenueMyIndexRoute = VenueMyIndexRouteImport.update({
  id: '/my/',
  path: '/my/',
  getParentRoute: () => VenueRouteRoute,
} as any)
const VenueFindIndexRoute = VenueFindIndexRouteImport.update({
  id: '/find/',
  path: '/find/',
  getParentRoute: () => VenueRouteRoute,
} as any)
const VenueSettingsPaymentRoute = VenueSettingsPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => VenueSettingsRouteRoute,
} as any)
const VenueFindVenueIdRoute = VenueFindVenueIdRouteImport.update({
  id: '/find/venue/$id',
  path: '/find/venue/$id',
  getParentRoute: () => VenueRouteRoute,
} as any)
const VenueFindConcertIdRoute = VenueFindConcertIdRouteImport.update({
  id: '/find/concert/$id',
  path: '/find/concert/$id',
  getParentRoute: () => VenueRouteRoute,
} as any)
const VenueFindArtistIdRoute = VenueFindArtistIdRouteImport.update({
  id: '/find/artist/$id',
  path: '/find/artist/$id',
  getParentRoute: () => VenueRouteRoute,
} as any)
const VenueApplicationsApplicationIdCheckoutRoute =
  VenueApplicationsApplicationIdCheckoutRouteImport.update({
    id: '/applications/$applicationId/checkout',
    path: '/applications/$applicationId/checkout',
    getParentRoute: () => VenueRouteRoute,
  } as any)
const VenueApplicationsApplicationIdAcceptRoute =
  VenueApplicationsApplicationIdAcceptRouteImport.update({
    id: '/applications/$applicationId/accept',
    path: '/applications/$applicationId/accept',
    getParentRoute: () => VenueRouteRoute,
  } as any)
const VenueMyOpportunitiesOpportunityIdApplicationsRoute =
  VenueMyOpportunitiesOpportunityIdApplicationsRouteImport.update({
    id: '/my/opportunities/$opportunityId/applications',
    path: '/my/opportunities/$opportunityId/applications',
    getParentRoute: () => VenueRouteRoute,
  } as any)
const VenueMyConcertsConcertIdRoute =
  VenueMyConcertsConcertIdRouteImport.update({
    id: '/my/concerts/concert/$id',
    path: '/my/concerts/concert/$id',
    getParentRoute: () => VenueRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof VenueIndexRoute
  '/fail': typeof FailRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/stripe-refresh': typeof StripeRefreshRoute
  '/stripe-return': typeof StripeReturnRoute
  '/success': typeof SuccessRoute
  '/settings': typeof VenueSettingsRouteRouteWithChildren
  '/create': typeof VenueCreateRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/settings/payment': typeof VenueSettingsPaymentRoute
  '/find/': typeof VenueFindIndexRoute
  '/my/': typeof VenueMyIndexRoute
  '/settings/': typeof VenueSettingsIndexRoute
  '/applications/$applicationId/accept': typeof VenueApplicationsApplicationIdAcceptRoute
  '/applications/$applicationId/checkout': typeof VenueApplicationsApplicationIdCheckoutRoute
  '/find/artist/$id': typeof VenueFindArtistIdRoute
  '/find/concert/$id': typeof VenueFindConcertIdRoute
  '/find/venue/$id': typeof VenueFindVenueIdRoute
  '/my/concerts/concert/$id': typeof VenueMyConcertsConcertIdRoute
  '/my/opportunities/$opportunityId/applications': typeof VenueMyOpportunitiesOpportunityIdApplicationsRoute
}
export interface FileRoutesByTo {
  '/fail': typeof FailRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/stripe-refresh': typeof StripeRefreshRoute
  '/stripe-return': typeof StripeReturnRoute
  '/success': typeof SuccessRoute
  '/create': typeof VenueCreateRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof VenueIndexRoute
  '/settings/payment': typeof VenueSettingsPaymentRoute
  '/find': typeof VenueFindIndexRoute
  '/my': typeof VenueMyIndexRoute
  '/settings': typeof VenueSettingsIndexRoute
  '/applications/$applicationId/accept': typeof VenueApplicationsApplicationIdAcceptRoute
  '/applications/$applicationId/checkout': typeof VenueApplicationsApplicationIdCheckoutRoute
  '/find/artist/$id': typeof VenueFindArtistIdRoute
  '/find/concert/$id': typeof VenueFindConcertIdRoute
  '/find/venue/$id': typeof VenueFindVenueIdRoute
  '/my/concerts/concert/$id': typeof VenueMyConcertsConcertIdRoute
  '/my/opportunities/$opportunityId/applications': typeof VenueMyOpportunitiesOpportunityIdApplicationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_venue': typeof VenueRouteRouteWithChildren
  '/fail': typeof FailRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/stripe-refresh': typeof StripeRefreshRoute
  '/stripe-return': typeof StripeReturnRoute
  '/success': typeof SuccessRoute
  '/_venue/settings': typeof VenueSettingsRouteRouteWithChildren
  '/_venue/create': typeof VenueCreateRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_venue/': typeof VenueIndexRoute
  '/_venue/settings/payment': typeof VenueSettingsPaymentRoute
  '/_venue/find/': typeof VenueFindIndexRoute
  '/_venue/my/': typeof VenueMyIndexRoute
  '/_venue/settings/': typeof VenueSettingsIndexRoute
  '/_venue/applications/$applicationId/accept': typeof VenueApplicationsApplicationIdAcceptRoute
  '/_venue/applications/$applicationId/checkout': typeof VenueApplicationsApplicationIdCheckoutRoute
  '/_venue/find/artist/$id': typeof VenueFindArtistIdRoute
  '/_venue/find/concert/$id': typeof VenueFindConcertIdRoute
  '/_venue/find/venue/$id': typeof VenueFindVenueIdRoute
  '/_venue/my/concerts/concert/$id': typeof VenueMyConcertsConcertIdRoute
  '/_venue/my/opportunities/$opportunityId/applications': typeof VenueMyOpportunitiesOpportunityIdApplicationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fail'
    | '/login'
    | '/register'
    | '/stripe-refresh'
    | '/stripe-return'
    | '/success'
    | '/settings'
    | '/create'
    | '/auth/callback'
    | '/settings/payment'
    | '/find/'
    | '/my/'
    | '/settings/'
    | '/applications/$applicationId/accept'
    | '/applications/$applicationId/checkout'
    | '/find/artist/$id'
    | '/find/concert/$id'
    | '/find/venue/$id'
    | '/my/concerts/concert/$id'
    | '/my/opportunities/$opportunityId/applications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/fail'
    | '/login'
    | '/register'
    | '/stripe-refresh'
    | '/stripe-return'
    | '/success'
    | '/create'
    | '/auth/callback'
    | '/'
    | '/settings/payment'
    | '/find'
    | '/my'
    | '/settings'
    | '/applications/$applicationId/accept'
    | '/applications/$applicationId/checkout'
    | '/find/artist/$id'
    | '/find/concert/$id'
    | '/find/venue/$id'
    | '/my/concerts/concert/$id'
    | '/my/opportunities/$opportunityId/applications'
  id:
    | '__root__'
    | '/_venue'
    | '/fail'
    | '/login'
    | '/register'
    | '/stripe-refresh'
    | '/stripe-return'
    | '/success'
    | '/_venue/settings'
    | '/_venue/create'
    | '/auth/callback'
    | '/_venue/'
    | '/_venue/settings/payment'
    | '/_venue/find/'
    | '/_venue/my/'
    | '/_venue/settings/'
    | '/_venue/applications/$applicationId/accept'
    | '/_venue/applications/$applicationId/checkout'
    | '/_venue/find/artist/$id'
    | '/_venue/find/concert/$id'
    | '/_venue/find/venue/$id'
    | '/_venue/my/concerts/concert/$id'
    | '/_venue/my/opportunities/$opportunityId/applications'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  VenueRouteRoute: typeof VenueRouteRouteWithChildren
  FailRoute: typeof FailRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  StripeRefreshRoute: typeof StripeRefreshRoute
  StripeReturnRoute: typeof StripeReturnRoute
  SuccessRoute: typeof SuccessRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stripe-return': {
      id: '/stripe-return'
      path: '/stripe-return'
      fullPath: '/stripe-return'
      preLoaderRoute: typeof StripeReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stripe-refresh': {
      id: '/stripe-refresh'
      path: '/stripe-refresh'
      fullPath: '/stripe-refresh'
      preLoaderRoute: typeof StripeRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fail': {
      id: '/fail'
      path: '/fail'
      fullPath: '/fail'
      preLoaderRoute: typeof FailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_venue': {
      id: '/_venue'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof VenueRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_venue/': {
      id: '/_venue/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof VenueIndexRouteImport
      parentRoute: typeof VenueRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_venue/create': {
      id: '/_venue/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof VenueCreateRouteImport
      parentRoute: typeof VenueRouteRoute
    }
    '/_venue/settings': {
      id: '/_venue/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof VenueSettingsRouteRouteImport
      parentRoute: typeof VenueRouteRoute
    }
    '/_venue/settings/': {
      id: '/_venue/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof VenueSettingsIndexRouteImport
      parentRoute: typeof VenueSettingsRouteRoute
    }
    '/_venue/my/': {
      id: '/_venue/my/'
      path: '/my'
      fullPath: '/my/'
      preLoaderRoute: typeof VenueMyIndexRouteImport
      parentRoute: typeof VenueRouteRoute
    }
    '/_venue/find/': {
      id: '/_venue/find/'
      path: '/find'
      fullPath: '/find/'
      preLoaderRoute: typeof VenueFindIndexRouteImport
      parentRoute: typeof VenueRouteRoute
    }
    '/_venue/settings/payment': {
      id: '/_venue/settings/payment'
      path: '/payment'
      fullPath: '/settings/payment'
      preLoaderRoute: typeof VenueSettingsPaymentRouteImport
      parentRoute: typeof VenueSettingsRouteRoute
    }
    '/_venue/find/venue/$id': {
      id: '/_venue/find/venue/$id'
      path: '/find/venue/$id'
      fullPath: '/find/venue/$id'
      preLoaderRoute: typeof VenueFindVenueIdRouteImport
      parentRoute: typeof VenueRouteRoute
    }
    '/_venue/find/concert/$id': {
      id: '/_venue/find/concert/$id'
      path: '/find/concert/$id'
      fullPath: '/find/concert/$id'
      preLoaderRoute: typeof VenueFindConcertIdRouteImport
      parentRoute: typeof VenueRouteRoute
    }
    '/_venue/find/artist/$id': {
      id: '/_venue/find/artist/$id'
      path: '/find/artist/$id'
      fullPath: '/find/artist/$id'
      preLoaderRoute: typeof VenueFindArtistIdRouteImport
      parentRoute: typeof VenueRouteRoute
    }
    '/_venue/applications/$applicationId/checkout': {
      id: '/_venue/applications/$applicationId/checkout'
      path: '/applications/$applicationId/checkout'
      fullPath: '/applications/$applicationId/checkout'
      preLoaderRoute: typeof VenueApplicationsApplicationIdCheckoutRouteImport
      parentRoute: typeof VenueRouteRoute
    }
    '/_venue/applications/$applicationId/accept': {
      id: '/_venue/applications/$applicationId/accept'
      path: '/applications/$applicationId/accept'
      fullPath: '/applications/$applicationId/accept'
      preLoaderRoute: typeof VenueApplicationsApplicationIdAcceptRouteImport
      parentRoute: typeof VenueRouteRoute
    }
    '/_venue/my/opportunities/$opportunityId/applications': {
      id: '/_venue/my/opportunities/$opportunityId/applications'
      path: '/my/opportunities/$opportunityId/applications'
      fullPath: '/my/opportunities/$opportunityId/applications'
      preLoaderRoute: typeof VenueMyOpportunitiesOpportunityIdApplicationsRouteImport
      parentRoute: typeof VenueRouteRoute
    }
    '/_venue/my/concerts/concert/$id': {
      id: '/_venue/my/concerts/concert/$id'
      path: '/my/concerts/concert/$id'
      fullPath: '/my/concerts/concert/$id'
      preLoaderRoute: typeof VenueMyConcertsConcertIdRouteImport
      parentRoute: typeof VenueRouteRoute
    }
  }
}

interface VenueSettingsRouteRouteChildren {
  VenueSettingsPaymentRoute: typeof VenueSettingsPaymentRoute
  VenueSettingsIndexRoute: typeof VenueSettingsIndexRoute
}

const VenueSettingsRouteRouteChildren: VenueSettingsRouteRouteChildren = {
  VenueSettingsPaymentRoute: VenueSettingsPaymentRoute,
  VenueSettingsIndexRoute: VenueSettingsIndexRoute,
}

const VenueSettingsRouteRouteWithChildren =
  VenueSettingsRouteRoute._addFileChildren(VenueSettingsRouteRouteChildren)

interface VenueRouteRouteChildren {
  VenueSettingsRouteRoute: typeof VenueSettingsRouteRouteWithChildren
  VenueCreateRoute: typeof VenueCreateRoute
  VenueIndexRoute: typeof VenueIndexRoute
  VenueFindIndexRoute: typeof VenueFindIndexRoute
  VenueMyIndexRoute: typeof VenueMyIndexRoute
  VenueApplicationsApplicationIdAcceptRoute: typeof VenueApplicationsApplicationIdAcceptRoute
  VenueApplicationsApplicationIdCheckoutRoute: typeof VenueApplicationsApplicationIdCheckoutRoute
  VenueFindArtistIdRoute: typeof VenueFindArtistIdRoute
  VenueFindConcertIdRoute: typeof VenueFindConcertIdRoute
  VenueFindVenueIdRoute: typeof VenueFindVenueIdRoute
  VenueMyConcertsConcertIdRoute: typeof VenueMyConcertsConcertIdRoute
  VenueMyOpportunitiesOpportunityIdApplicationsRoute: typeof VenueMyOpportunitiesOpportunityIdApplicationsRoute
}

const VenueRouteRouteChildren: VenueRouteRouteChildren = {
  VenueSettingsRouteRoute: VenueSettingsRouteRouteWithChildren,
  VenueCreateRoute: VenueCreateRoute,
  VenueIndexRoute: VenueIndexRoute,
  VenueFindIndexRoute: VenueFindIndexRoute,
  VenueMyIndexRoute: VenueMyIndexRoute,
  VenueApplicationsApplicationIdAcceptRoute:
    VenueApplicationsApplicationIdAcceptRoute,
  VenueApplicationsApplicationIdCheckoutRoute:
    VenueApplicationsApplicationIdCheckoutRoute,
  VenueFindArtistIdRoute: VenueFindArtistIdRoute,
  VenueFindConcertIdRoute: VenueFindConcertIdRoute,
  VenueFindVenueIdRoute: VenueFindVenueIdRoute,
  VenueMyConcertsConcertIdRoute: VenueMyConcertsConcertIdRoute,
  VenueMyOpportunitiesOpportunityIdApplicationsRoute:
    VenueMyOpportunitiesOpportunityIdApplicationsRoute,
}

const VenueRouteRouteWithChildren = VenueRouteRoute._addFileChildren(
  VenueRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  VenueRouteRoute: VenueRouteRouteWithChildren,
  FailRoute: FailRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  StripeRefreshRoute: StripeRefreshRoute,
  StripeReturnRoute: StripeReturnRoute,
  SuccessRoute: SuccessRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
