global using Concertable.Kernel;
global using Concertable.Contracts;
global using Concertable.Kernel.Identity;
global using Concertable.Messaging;
global using Concertable.DataAccess;
global using Concertable.DataAccess.Infrastructure;
global using Concertable.Customer.User.Application.Interfaces;
global using Concertable.Customer.User.Contracts;
global using Concertable.Customer.User.Domain;
